# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
    ]
